version: "3"
services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    restart: on-failure
    container_name: cennz-api
    depends_on:
      - "db"
    ports:
      - "8080:80"
    volumes:
      - ./api/chalice-api:/chalice-api
    environment:
      DB_USERNAME: username
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: cennznetdata
      DB_SCHEMA: public
  db:
    image: postgres:10.7
    container_name: cennz-postgresql-db
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cennznetdata
    volumes:
      - ./api/ddl:/docker-entrypoint-initdb.d
    ports: 
      - "5433:5432"
  etl:
    build:
      context: etl
      dockerfile: Dockerfile
    depends_on:
      - "db"
      - "ws"
    container_name: cennz-etl
    restart: 
      always
  portal:
    build:
      context: portal
      dockerfile: Dockerfile
    restart: 
      always
    container_name: cennz-web-portal
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: local
    depends_on: 
      - "api"
      - "ws"
  ws:
    build:
      context: ws
      dockerfile: Dockerfile
    restart: 
      always
    container_name: cennz-websocket
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: local